Django-databaze/databaze/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse


def attachment_path(instance, filename):
    return 'film/' + str(instance.film.id) + '/attachments/' + filename


class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Genre name',
    help_text='Enter a film genre (e.g. sci-fi, comedy)')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Film(models.Model):
    title = models.CharField(max_length=200, verbose_name='Title')
    plot = models.TextField(blank=True, null=True, verbose_name='Plot')
    release_date = models.DateField(blank=True, null=True,
                                    help_text='Please use the following format: <em>YYYYMM-DD</em>.',
                                    verbose_name='Release date')
    runtime = models.IntegerField(blank=True, null=True,
                                  help_text='Please enter an integer value (minutes)',
                                  verbose_name='Runtime')
    poster = models.ImageField(upload_to='film/posters/%Y/%m/%d/', blank=True, null=True,
                               verbose_name="Poster")
    rate = models.FloatField(default=5.0,
                             validators=[MinValueValidator(1.0), MaxValueValidator(10.0)],
                             null=True, help_text='Please enter an float value (range 1.0 - 10.0)',
                             verbose_name='Rate')
    genres = models.ManyToManyField(Genre, help_text='Select a genre for this film')

    class Meta:
        ordering = ['-release_date', 'title']

    def __str__(self):
        return f'{self.title}, year: {str(self.release_date.year)}, rate:{str(self.rate)}'

    def get_absolute_url(self):
        return reverse('film-detail', args=[str(self.id)])


class Attachment(models.Model):
    title = models.CharField(max_length=200, verbose_name='Title')
    last_update = models.DateTimeField(auto_now=True)
    file = models.FileField(upload_to=attachment_path, null=True, verbose_name='File')
    TYPE_OF_ATTACHMENT = (
        ('audio', 'Audio'),
        ('image', 'Image'),
        ('text', 'Text'),
        ('video', 'Video'),
        ('other', 'Other'),
    )
    type = models.CharField(max_length=10, choices=TYPE_OF_ATTACHMENT, blank=True,
        default='image', help_text='Select allowed attachment type',
        verbose_name='Attachment type')
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-last_update', 'type']

    def __str__(self):
        return f'{self.title}, ({self.type})'

Django-databaze/databaze/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.decorators.cache import never_cache
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import FilmModelForm
from .models import Film, Genre, Attachment


def index(request):
    """Metoda připravuje pohled pro domovskou stránku - šablona index.html"""
    """ Do proměnné context, která je typu slovník (dictionary), přiřadíme jednotlivým klíčům informace získané z databáze
     pomocí ORM systému Djanga - využíváme jednotlivých datových modelů a pracujeme s nimi jako se sadami objektů """
    context = {
        # Výběr filmů podle data uvedení uspořádaný sestupně - 3 nejnovější filmy
        'films': Film.objects.order_by('-release_date')[:3],
        # Výběr deseti nejlepších filmů (uspořádány sestupně podle hodnocení)
        'top_ten': Film.objects.order_by('-rate').all()[:10],
        # Výběr všech žánrů uspořádaných abecedně podle názvu
        'genres': Genre.objects.order_by('name').all(),
    }

    """ Pomocí metody render vyrendrujeme šablonu index.html a předáme ji hodnoty v proměnné context k zobrazení """
    return render(request, 'index.html', context=context)


""" Třída dědí z generické třídy ListView, která umí vypsat z databáze všechny objekty určeného modelu """
class FilmListView(ListView):
    # Nastavení požadovaného modelu
    model = Film
    # Pojmenování objektu, v němž budou šabloně předána data z modelu (tj. databázové tabulky)
    context_object_name = 'films_list'
    # Umístění a název šablony
    template_name = 'film/list.html'
    paginate_by = 3

    # Metoda vrací sadu záznamů filtrovaných podle nastavení klíčového argumentu 'genre_name'
    def get_queryset(self):
        # Jestliže je v klíčových atributech předaných objektu (self.kwargs) zastoupen atribut 'genre_name' ...
        if 'genre_name' in self.kwargs:
            # ... z databáze jsou vybrány všechny objekty (filmy), patřící k žánru, na který klíčový atribut odkazuje
            # genres__name=self.kwargs['genre_name']
            return Film.objects.filter(genres__name=self.kwargs['genre_name']).all()
        else:
            # ... v opačném případě jsou vybrány všechny objekty (filmy)
            return Film.objects.all()

    # Metoda upravuje data předávaná šabloně prostřednictví proměnné context (typu dictionary)
    def get_context_data(self, **kwargs):
        # Nejprve je zavolána původní implementace metody, jak je řešena v třídě předka, který zastupuje dočasný objekt super()
        # (temporary object of the superclass)
        context = super().get_context_data(**kwargs)
        # Zjištění aktuálního počtu záznamů v dané datové sadě - len(self.get_queryset())
        context['num_films'] = len(self.get_queryset())
        # Jestliže je v klíčových atributech předaných objektu (self.kwargs) zastoupen atribut 'genre_name' ...
        if 'genre_name' in self.kwargs:
            # ... šabloně budou prostřednictvím kontextu předány proměnné 'view_title' a 'view_head', které budou obsahovat informace
            # o aktuálně vybraném žánru
            context['view_title'] = f"Žánr: {self.kwargs['genre_name']}"
            context['view_head'] = f"Žánr filmu: {self.kwargs['genre_name']}"
        else:
            # ... v opačném případě budou předány stejné proměnné s obecnějším popisem
            # o aktuálně vybraném žánru
            context['view_title'] = 'Filmy'
            context['view_head'] = 'Přehled filmů'
        return context


""" Třída dědí z generické třídy DetailView, která umí vypsat z databáze jeden objekt určeného modelu """
class FilmDetailView(DetailView):
    # Nastavení požadovaného modelu
    model = Film
    # Pojmenování objektu, v němž budou šabloně předána data z modelu (tj. databázové tabulky)
    context_object_name = 'film_detail'
    # Umístění a název šablony
    template_name = 'film/detail.html'


class GenreListView(ListView):
    model = Genre
    template_name = 'blocks/genre_list.html'
    context_object_name = 'genres'
    queryset = Genre.objects.order_by('name').all()


class FilmCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Film
    template_name = 'movies/film_form_crispy.html'
    fields = ['title', 'plot', 'release_date', 'runtime', 'poster', 'rate', 'genres']
    initial = {'rate': '5'}
    login_url = '/accounts/login/'
    permission_required = 'movies.add_film'

    def get_success_url(self):
        return reverse_lazy('film_detail', kwargs={'pk': self.object.pk})


class FilmUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Film
    template_name = 'movies/film_bootstrap_form.html'
    form_class = FilmModelForm
    #fields = '__all__' # Not recommended (potential security issue if more fields added)
    login_url = '/accounts/login/'
    permission_required = 'movies.change_film'

    def get_success_url(self):
        return reverse_lazy('film_detail', kwargs={'pk': self.object.pk})


class FilmDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Film
    success_url = reverse_lazy('films')
    login_url = '/accounts/login/'
    permission_required = 'movies.delete_film'


def error_404(request, exception=None):
        return render(request, 'errors/404.html')


def error_500(request):
    return render(request, 'errors/500.html')


def error_403(request, exception=None):
    return render(request, 'errors/403.html')


def error_400(request, exception=None):
    return render(request, 'errors/400.html')


@never_cache
def clear_cache(request):
    if not request.user.is_superuser:
        raise PermissionDenied
    cache.clear()
    return HttpResponse('Cache has been cleared')

Django-databaze/databaze/templates/base.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <!-- Blok s titulkem stránky -->
    <title>{% block title %}Filmotéka{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Připojení externích CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- Načtení adresy statických souborů webu - musí být před prvním použití identifikátoru static -->
    {% load static %}
    <!-- Blok určený k připojování dalších externích stylů -->
    {% block css %}
    {% endblock %}
    <!-- Připojení vlastního CSS souboru umístěného ve struktuře složky static -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <!-- Záhlaví stránky -->
    {% block header %}
        {% include "page/header.html" %}
    {% endblock %}
    <!-- Navigační lišta -->
    {% block navbar %}
        {% include "page/navbar.html" %}
    {% endblock %}
    <!-- Hlavní blok stránky -->
    <main>
        <div class="container-fluid">
            <!-- Zde bude vsunut blok s obsahem aktuální stránky -->
            {% block content %}{% endblock %}
        </div>
    </main>
    <!-- Zápatí stránky -->
    {% block footer %}
        {% include "page/footer.html" %}
    {% endblock %}
    <!-- Připojení externích JS knihoven -->
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <!-- Připravený blok pro vložení/připojení dalších skriptů podle potřeby jednotlivých stránek -->
    {% block scripts %}{% endblock %}
</body>
</html>

Django-databaze/databaze/templates/blocks/genre_list.html
<ul class="list-group">
    {% for genre in genres %}
    <li class="list-group-item list-group-item-info"><a class="text-dark" href="{% url 'film-genre' genre.name %}">{{ genre.name }}</a>
        <span class="badge badge-dark">{{ genre.film_set.all.count }}</span></li>
    {% endfor %}
</ul>

Django-databaze/databaze/templates/blocks/new_films.html
{% load mathfilters %}

<div>
    {% for film in films %}
        <div class="row mb-4 border-bottom">
            <div class="col-md-2">
                {% if film.poster %}
                    <a href="{% url 'film_detail' film.pk %}">
                    <img src="{{ film.poster.url }}" alt="{{ film.title }}"
                         class="img-fluid">
                    </a>
                {% else %}
                    <a href="{% url 'film_detail' film.pk %}">Plakát k filmu není k dispozici</a>
                {% endif %}
            </div>
            <div class="col-md-8">
                <h4><a href="{% url 'film_detail' film.pk %}">{{ film.title|upper }}</a></h4>
                <p>{{ film.plot|truncatewords:30 }}</p>
                <p>Stopáž: {{ film.runtime }} min.,
                    datum uvedení: {{ film.release_date|date:'d. m. Y' }}</p>
                <p>Žánry: {% for genre in film.genres.all %}
                    <a href="#" class="btn btn-info">{{ genre.name }}</a>
                {% endfor %}</p>
            </div>
            <div class="col-md-2">
                <span class="display-4">{{ film.rate }}</span>
                <div class="progress">
                    <div class="progress-bar bg-info"
                         style="width:{{ film.rate|mul:'10'|floatformat }}%"></div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

Django-databaze/databaze/templates/blocks/top_ten.html
<ol class="list-group">
    {% for film in top_ten %}
    <li class="list-group-item list-group-item-danger d-flex justify-content-between align-items-center"><a class="text-dark" href="{% url 'film_detail' film.id %}">{{ film.title }}</a> <span class="badge badge-pill badge-danger">{{ film.rate }}</span></li>
    {% endfor %}
</ol>

Django-databaze/databaze/templates/film/detail.html
{% extends "base.html" %}
{% block title %}Detail filmu{% endblock %}

<!-- Vložení externího CSS pro knihovnu Lightbox for Bootstrap -->
{% block css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Podrobné informace</h2>
    </div>
</div>
<div class="row mt-5 mb-3">
    <div class="col-lg-6 mb-3">
        <h2 class="display-4 mb-3">{{ film_detail.title }}</h2>
        <div class="bg-secondary text-light p-2 mb-3">Rok vzniku: {{ film_detail.release_date.year }}, stopáž: {{ film_detail.runtime }} minut,
            <!-- Řešení zobrazení hodnocení filmu ve formě hvězdiček -->
            {% with ''|center:film_detail.rate as range %}
            {% for _ in range %}★{% endfor %}
            {% endwith %}
            <b>{{ film_detail.rate }}</b>
        </div>
        <div class="row">
            <div class="col-md-9">{{ film_detail.plot }}</div>
            <div class="col-md-3">
                {% if film_detail.poster %}
                <!-- Úprava odkazu pro knihovnu Lightbox for Bootstrap -->
                 <a href="{{ film_detail.poster.url }}" data-toggle="lightbox" data-gallery="gallery">
                    <img src="{{ film_detail.poster.url }}" class="img-fluid" alt="Plakát k filmu">
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg-6 bg-light p-3">
        <h3 class="border-bottom pb-3 text-secondary text-center text-uppercase">Fotogalerie</h3>
        <div class="row">
        <!-- Zobrazení fotogalerie k příslušnému filmu -->
        {% for image in film_detail.attachment_set.all %}
            <div class="col-lg-6 col-xl-4">
                <!-- Úprava odkazu pro knihovnu Lightbox for Bootstrap -->
                <a href="{{ image.file.url }}" data-toggle="lightbox" data-gallery="gallery">
                    <img src="{{ image.file.url }}" class="img-fluid img-thumbnail" alt="{{ image.title }}">
                </a>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
<div class="row mb-3">
    <div class="col-sm-12 text-center">
        <a href="{% url 'film_update' film_detail.pk %}" class="btn btn-primary">Upravit</a>
        <a href="{% url 'film_delete' film_detail.pk %}" class="btn btn-danger">Smazat</a>
    </div>
</div>
{% endblock %}

<!-- Vložení externího JS pro knihovnu Lightbox for Bootstrap -->
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>
<script>
    $(document).on("click", '[data-toggle="lightbox"]', function(event) {
        event.preventDefault();
        $(this).ekkoLightbox();
    });
</script>
{% endblock %}

Django-databaze/databaze/templates/film/list.html
<!-- Dědí základní šablonu base.html -->
{% extends "base.html" %}

<!-- Vložení informace do bloku titulu stránky -->
{% block title %}{{ view_title }}{% endblock %}

<!-- Obsahový blok stránky -->
{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">{{ view_head }}</h2>
    </div>
</div>
<div class="row">
    <!-- Postupné načtení filmů z proměnné films_list -->
    {% for film in films_list %}
    <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2">
        <div class="card">
            {% if film.poster %}
                <img class="card-img-top" src="{{ film.poster.url }}" alt="{{ film.title }}">
            {% endif %}
            <div class="card-body">
                <!-- Odkaz ještě musí být doplněn o adresu stránky s detailem filmu -->
                <h4 class="card-title"><a href="{% url 'film_detail' film.pk %}">{{ film.title }}</a></h4>
                <!-- Výpis všech žánrů filmu - odkaz bude posléze ukazovat všechny filmy daného žánru -->
                <p class="card-text">{% for genre in film.genres.all %}<a href="{% url 'film-genre' genre.name %}" class="btn btn-light">{{ genre.name }}</a> {% endfor %}</p>
                <!-- Odkaz ještě musí být doplněn o adresu stránky s detailem filmu -->
                <a href="{% url 'film_detail' film.pk %}" class="btn btn-primary">Podrobnosti</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="row mb-3">
    <div class="col-sm-12 text-center">
        <a href="{% url 'film_create' %}" class="btn btn-success">Nový film</a>
    </div>
</div>
{% endblock %}

Django-databaze/databaze/templates/index.html
<!-- Šablona dědí základní šablonu "base.html" -->
{% extends "base.html" %}

<!-- Do bloku content vsuneme následující kód  -->
{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Úvodní stránka</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h2 class="text-center bg-success text-light p-2">Filmové novinky</h2>
        {% include "blocks/new_films.html" %}
    </div>
    <div class="col-md-3">
        <h2 class="text-center bg-danger text-light p-2">Top deset filmů</h2>
        {% include "blocks/top_ten.html" %}
    </div>
    <div class="col-md-3">
        <h2 class="text-center bg-info text-light p-2">Filmové žánry</h2>
        {% include "blocks/genre_list.html" %}
    </div>
</div>
<div class="row">
</div>
{% endblock %}

Django-databaze/databaze/templates/movies/film_bootstrap_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Editace filmu{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Editace filmu</h2>
    </div>
</div>
<div class="row mt-5 mb-3">
    <div class="container">
        <form method="post" novalidate>
            {% csrf_token %}

            {% for hidden_field in form.hidden_fields %}
              {{ hidden_field }}
            {% endfor %}

            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                  {{ error }}
                {% endfor %}
            </div>
            {% endif %}

            {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}
                  {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                      <div class="invalid-feedback">
                          {{ error }}
                      </div>
                    {% endfor %}
                  {% else %}
                    {% render_field field class="form-control is-valid" %}
                  {% endif %}
                {% else %}
                  {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
            {% endfor %}

            <button class="btn btn-primary" type="submit">Potvrdit</button>
            <button class="btn btn-secondary" onclick="javascript:history.back();">Zrušit</button>
        </form>
    </div>
</div>
{% endblock %}

Django-databaze/databaze/templates/movies/film_confirm_delete.html
{% extends "base.html" %}
{% block title %}Smazání filmu{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Smazání filmu</h2>
    </div>
</div>
<div class="row mt-5 mb-3">
    <div class="col-sm-12 alert alert-danger text-center">
        <h4>Určitě chcete smazat tento film: {{ film }}?</h4>
        <form action="" method="POST">
          {% csrf_token %}
          <input type="submit" class="btn btn-danger" value="Ano, smazat.">
        </form>
    </div>
</div>
{% endblock %}

Django-databaze/databaze/templates/movies/film_form.html
{% extends "base.html" %}

{% block title %}Editace filmu{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Editace filmu</h2>
    </div>
</div>
<div class="row mt-5 mb-3">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
</div>
{% endblock %}

Django-databaze/databaze/templates/movies/film_form_crispy.html
{# https://simpleisbetterthancomplex.com/tutorial/2018/08/13/how-to-use-bootstrap-4-forms-with-django.html #}
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Editace filmu{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Editace filmu</h2>
    </div>
</div>
<div class="row mt-5 mb-3">
  <div class="col-12">
  <form action="" method="post" enctype="multipart/form-data" class="container">
    {% csrf_token %}
    {{ form|crispy }}
      <button type="submit" class="btn btn-success">Odeslat</button>
  </form>
  </div>
</div>
{% endblock %}

Django-databaze/databaze/templates/movies/film_form_crispy_own.html
{# https://www.geeksforgeeks.org/render-django-form-fields-manually/ #}
{# https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html #}

{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block title %}Editace filmu{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Editace filmu</h2>
    </div>
</div>
<div class="row mt-5 mb-3">
  <div class="col-12">
  <form action="" method="post" enctype="multipart/form-data" class="container" novalidate>
    {% csrf_token %}
      <div class="form-group">
          <label class="col-md-2">{{ form.title.label }}</label>
          <div class="col-md-10">
            {% render_field form.title class="form-control" %}
          </div>
      </div>
    {{ form.title|as_crispy_field }}
      <button type="submit" class="btn btn-success">Odeslat</button>
  </form>
  </div>
</div>
{% endblock %}

Django-databaze/databaze/templates/page/footer.html
{% load static %}
<footer class="container-fluid text-center">
    <hr>
    <!-- Vykreslí logo školy ze statického souboru skola-logo.png -->
    <p><img src="{% static 'img/skola-logo.png' %}" alt="Logo školy"></p>
    <p>&copy; 2021 - SŠPU Opava</p>
</footer>

Django-databaze/databaze/templates/page/header.html
<header class="jumbotron-fluid p-5 text-center bg-dark">
    <h1 class="text-white text-uppercase display-3">Malá filmová databáze</h1>
</header>

Django-databaze/databaze/templates/page/navbar.html
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <!-- Brand -->
    <a class="navbar-brand text-warning" href="#">MFD</a>

    <!-- Přepínací tlačítko pro mobilní zobrazení -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Hlavní menu -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <!-- Odkaz na úvodní stránku webu -->
                <a class="nav-link active" href="{% url 'index' %}">Úvodní stránka</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'films' %}">Filmy</a>
            </li>
            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    Žánry
                </a>
                <div class="dropdown-menu">
                    {% for genre in genres %}
                        <a class="dropdown-item" href="{% url 'film-genre' genre.name %}">{{ genre.name }}</a>
                    {% endfor %}
                </div>
            </li>
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'index' %}" class="nav-link">User: {{ user.get_username }}</a></li>
                <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
            {% else %}
                <li class="nav-item"><a href="{% url 'login' %}?next={{ request.path }}" class="nav-link">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>